# Generated by Django 2.2.3 on 2020-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.FilePathField(path='/img'),
        ),
    ]
